// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NotificationPreview } from "./NotificationPreview";
import type { PeerRetention } from "./PeerRetention";
import type { PeerSecurityMinimum } from "./PeerSecurityMinimum";

/**
 * The account's settings the agent acts on with no window open. Every field is
 * stated by the UI that pushes them; the agent supplies no defaults of its own
 * beyond the UI's documented ones (`AccountPreferences::UI_DEFAULTS`).
 */
export type AccountPreferences = { send_read_receipts: boolean, accept_requests_from_strangers: boolean, notify_on_screenshot: boolean, notification_preview: NotificationPreview, retention: Array<PeerRetention>, 
/**
 * Chats with a level above Standard; an absent chat admits every offer.
 * Absent from a UI that predates it, which pushed no minimum.
 */
security_minimums: Array<PeerSecurityMinimum>, };
