// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Accounts = { cid: bigint, accounts: Record<string, AccountInformation>, request_id: string | null, };
