// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PeerSessionInformation } from "./PeerSessionInformation";

export type AccountInformation = { username: string, full_name: string, peers: Record<string, PeerSessionInformation>, };
