// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountPreferences } from "./AccountPreferences";

export type AccountPreferencesResponse = { cid: bigint, preferences: AccountPreferences, request_id: string | null, };
