// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A signed-in account, as the menu-bar app lists it.
 */
export type AccountRow = { cid: bigint, username: string, server_host: string | null, 
/**
 * Unread messages across the account's conversations.
 */
unread: number, muted: boolean, };
