// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Present only when this agent offers agent-hosted ILM.
 */
export type AgentIlmOffer = { 
/**
 * The accounts whose ILM this agent is hosting right now, ascending. A
 * browser that finds its CID here must not start its own ILM for it: the
 * agent's survives a page reload, and two ILMs must never run for one
 * account.
 */
hosted: Array<bigint>, };
