// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The answer to `DeclareCapabilities`: what this agent offers.
 */
export type AgentCapabilities = { 
/**
 * Always 0: capabilities belong to the agent, not to a session.
 */
cid: bigint, 
/**
 * The agent hosts each session's ILM for a client that declared it.
 */
agent_ilm: boolean, 
/**
 * A session may be attached to several connections (`AttachSession`).
 */
multi_window: boolean, 
/**
 * The agent keeps this account's peers connected itself; see
 * `ServiceConnectionAccepted::supervises_p2p`.
 */
supervises_p2p: boolean, 
/**
 * Something on the agent's side shows its native notices: the menu-bar app
 * is subscribed. Kept current by `NoticesHeardNotification`. Absent from an
 * older agent, which is what `false` means here.
 */
notices_heard: boolean, request_id: string | null, };
