// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The answer to `DeclareCapabilities`: what this agent offers.
 */
export type AgentCapabilities = { 
/**
 * Always 0: capabilities belong to the agent, not to a session.
 */
cid: bigint, 
/**
 * The agent hosts each session's ILM for a client that declared it.
 */
agent_ilm: boolean, 
/**
 * A session may be attached to several connections (`AttachSession`).
 */
multi_window: boolean, request_id: string | null, };
