// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What proves a caller may join a session another connection holds.
 */
export type AttachProof = { "Password": number[] } | { "Token": number[] };
