// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Attachment = { file_id: string, file_name: string, file_size: number, file_type: string, thumbnail?: string, };
