// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InternalServiceResponse } from "./InternalServiceResponse";

/**
 * Response from a batched request containing results in the same order as input commands
 */
export type BatchedResponseData = { 
/**
 * CID is 0 for batched responses (batch is not tied to a single session)
 */
cid: bigint, request_id: string | null, results: Array<InternalServiceResponse>, };
