// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a connection's client can do, declared once per connection.
 *
 * A client that declares `agent_ilm` never runs an ILM of its own for a
 * session: it sends reliable messages with `SendReliable` and the agent hosts
 * the session's ILM. A client that declares nothing is treated as one that
 * predates this (citadel-workspace `docs/plans/multi-window-sessions.md`).
 */
export type ClientCapabilities = { agent_ilm: boolean, };
