// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConversationMetadata } from "./ConversationMetadata";
import type { ConversationPage } from "./ConversationPage";

export type ConversationPageResponse = { cid: bigint, peer_cid: bigint, metadata: ConversationMetadata | null, page: ConversationPage | null, request_id: string | null, };
