// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConversationEventKind } from "./ConversationEventKind";
import type { ConversationMessage } from "./ConversationMessage";
import type { ConversationMetadata } from "./ConversationMetadata";

/**
 * Something changed in one of the account's conversations. Sent to every
 * window attached to the session; a window that sees a gap in `seq` re-reads
 * the conversation with `ConversationPage`.
 */
export type ConversationEvent = { cid: bigint, peer_cid: bigint, 
/**
 * Per account, increasing by one per event.
 */
seq: bigint, kind: ConversationEventKind, message: ConversationMessage | null, message_id: string | null, metadata: ConversationMetadata | null, 
/**
 * For a native notification (phase 6): whose account, and from whom.
 */
account_username: string, peer_username: string | null, 
/**
 * The first 100 characters of an appended message's text.
 */
preview: string, request_id: string | null, };
