// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConversationMessage } from "./ConversationMessage";
import type { PageTimestamps } from "./PageTimestamps";

export type ConversationPage = { peerCid: bigint, pageNumber: number, messages: Array<ConversationMessage>, pageTimestamps: PageTimestamps, };
