// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConversationMetadata } from "./ConversationMetadata";

export type ConversationListResponse = { cid: bigint, conversations: Array<ConversationMetadata>, request_id: string | null, };
