// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConversationMessage } from "./ConversationMessage";

/**
 * A request about a conversation succeeded; carries the message it touched.
 */
export type ConversationUpdated = { cid: bigint, peer_cid: bigint, message: ConversationMessage | null, request_id: string | null, };
