// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ConversationMetadata = { peerCid: bigint, ownerCid?: bigint, peerUsername?: string, totalMessageCount: number, oldestMessageTimestamp: number, newestMessageTimestamp: number, latestPage: number, messagesPerPage: number, unreadCount: number, lastMessageIndex: number, lastUpdated: number, };
