// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Attachment } from "./Attachment";
import type { MessageStatus } from "./MessageStatus";
import type { MessageType } from "./MessageType";
import type { Reaction } from "./Reaction";
import type { TransferMode } from "./TransferMode";
import type { TransferState } from "./TransferState";

/**
 * One message in a conversation.
 */
export type ConversationMessage = { id: string, content: string, senderCid: bigint, recipientCid: bigint, timestamp: number, index: number, status: MessageStatus, error?: string, replyTo?: string, edited_at?: number, reactions?: Array<Reaction>, mentions?: Array<string>, attachments?: Array<Attachment>, message_type: MessageType, document_id?: string, document_title?: string, transfer_id?: string, file_name?: string, file_size?: number, file_type?: string, file_thumbnail?: string, transfer_mode?: TransferMode, transfer_state?: TransferState, transfer_progress?: number, virtual_path?: string, };
