// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DisconnectNotification = { cid: bigint, peer_cid: bigint | null, request_id: string | null, 
/**
 * Set when the session was ended on this device only: the server could not be told (its
 * link was down, or it did not answer), so it learns of the sign-out when the account next
 * connects. Carries why. `None` for a sign-out the server acknowledged.
 */
ended_locally?: string, };
