// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EnableAgentIlmSuccess = { cid: bigint, 
/**
 * True when the agent was already hosting this account's ILM, which is
 * what a reloaded page finds. The opt-in is idempotent: either way the
 * agent's ILM is the one running when this arrives.
 */
already_hosted: boolean, request_id: string | null, };
