// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A failure the UI can act on, beside the message it shows.
 */
export type FailureReason = "admission_required" | "admission_failed";
