// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ObjectTransferStatus } from '@avarok/citadel-protocol-types';

export type FileTransferTickNotification = { cid: bigint, peer_cid: bigint | null, status: ObjectTransferStatus, request_id: string | null, };
