// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VirtualObjectMetadata } from '@avarok/citadel-protocol-types';

export type FileTransferRequestNotification = { cid: bigint, peer_cid: bigint, metadata: VirtualObjectMetadata, request_id: string | null, };
