// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FileTransferTickNotification = { cid: bigint, peer_cid: bigint | null, status: any, request_id: string | null, };
