// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Source for file transfer operations.
 * Allows either a direct file path or a reference to a previously picked file.
 */
export type FileSource = { "Path": string } | { "PickFileRef": { pick_file_request_id: string, } };
