// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FileTransferStatusNotification = { cid: bigint, object_id: any, success: boolean, response: boolean, message: string | null, request_id: string | null, };
