// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ObjectId } from '@avarok/citadel-protocol-types';

export type FileTransferStatusNotification = { cid: bigint, object_id: ObjectId, success: boolean, response: boolean, message: string | null, request_id: string | null, };
