// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentIlmOffer } from "./AgentIlmOffer";
import type { SessionInformation } from "./SessionInformation";

export type GetSessionsResponse = { cid: bigint, sessions: Array<SessionInformation>, request_id: string | null, 
/**
 * `Some` only from an agent that offers agent-hosted ILM (see agent_ilm.rs).
 * Last, and defaulted, so a response from an older agent still parses.
 */
agent_ilm?: AgentIlmOffer | null, };
