// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionInformation } from "./SessionInformation";

export type GetSessionsResponse = { cid: bigint, sessions: Array<SessionInformation>, request_id: string | null, };
