// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionInformation } from "./SessionInformation";
import type { SignedOutSession } from "./SignedOutSession";

export type GetSessionsResponse = { cid: bigint, sessions: Array<SessionInformation>, 
/**
 * Accounts whose sessions the server ended, until each signs in again. Absent from an
 * older agent, hence the default.
 */
signed_out: Array<SignedOutSession>, request_id: string | null, };
