// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GroupListGroupsResponse = { cid: bigint, group_list: any[] | null, request_id: string | null, };
