// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MessageGroupKey } from '@avarok/citadel-protocol-types';

export type GroupMessageNotification = { cid: bigint, peer_cid: bigint, message: number[], group_key: MessageGroupKey, request_id: string | null, };
