import type { MessageGroupKey } from '@avarok/citadel-protocol-types';
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The groups this session is in -- owned or joined -- as the agent holds them.
 *
 * `GroupListGroupsFor` answers only for groups an owner created, so a member's
 * new browser had no way to learn the groups it was already in. The session's
 * live group channels are exactly that set.
 */
export type GroupListJoinedSuccess = { cid: bigint, groups: MessageGroupKey[], request_id: string | null, };
