// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GroupListGroupsSuccess = { cid: bigint, peer_cid: bigint | null, group_list: any[] | null, request_id: string | null, };
