import type { MessageGroupKey } from '@avarok/citadel-protocol-types';
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PendingGroupInvite } from "./PendingGroupInvite";

/**
 * The groups this session is in -- owned or joined -- as the agent holds them.
 *
 * `GroupListGroupsFor` answers only for groups an owner created, so a member's
 * new browser had no way to learn the groups it was already in. The session's
 * live group channels are exactly that set.
 */
export type GroupListJoinedSuccess = { cid: bigint, groups: MessageGroupKey[], request_id: string | null, 
/**
 * Invitations this session has not answered, kept by the agent so one sent while no tab
 * was open is still shown. `None` from an older agent, which does not keep them; last and
 * defaulted, so that agent's response still parses.
 */
pending_invites?: Array<PendingGroupInvite>, };
