// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GroupRequestJoinSuccess = { cid: bigint, group_key: any, request_id: string | null, };
