// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MessageGroupKey } from '@avarok/citadel-protocol-types';

export type GroupListGroupsSuccess = { cid: bigint, peer_cid: bigint | null, group_list: MessageGroupKey[] | null, request_id: string | null, };
