import type { MessageGroupKey } from '@avarok/citadel-protocol-types';
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GroupRespondRequestSuccess = { cid: bigint, group_key: MessageGroupKey, request_id: string | null, };
