// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GroupMessageNotification = { cid: bigint, peer_cid: bigint, message: number[], group_key: any, request_id: string | null, };
