// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MessageGroupKey, MemberState } from '@avarok/citadel-protocol-types';

export type GroupMemberStateChangeNotification = { cid: bigint, group_key: MessageGroupKey, state: MemberState, request_id: string | null, };
