import type { MessageGroupKey } from '@avarok/citadel-protocol-types';
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GroupMessageDroppedNotification = { 
/**
 * The session the message was addressed to.
 */
cid: bigint, group_key: MessageGroupKey, 
/**
 * The CID of the member who sent the message.
 */
sender: bigint, 
/**
 * Why this session could not read it, as the SDK put it.
 */
reason: string, request_id: string | null, };
