// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GroupEndNotification = { cid: bigint, group_key: any, success: boolean, request_id: string | null, };
