// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One `RTCIceServer` entry. `credential` is a TURN password: redacted from `Debug`.
 */
export type IceServer = { urls: Array<string>, username: string | null, credential: string | null, };
