// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ListAllPeersResponse = { cid: bigint, peer_information: Record<string, PeerInformation>, request_id: string | null, };
