import type { PeerInformation } from "./PeerInformation";
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ListRegisteredPeersResponse = { cid: bigint, peers: Record<string, PeerInformation>, request_id: string | null, };
