// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LocalDBGetAllKVSuccess = { cid: bigint, peer_cid: bigint | null, map: Record<string, number[]>, request_id: string | null, };
