// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LocalDBClearAllKVFailure = { cid: bigint, peer_cid: bigint | null, message: string, request_id: string | null, };
