// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A media session could not be opened. Carries why, because "call failed" with
 * no reason is the least actionable thing a user can be told.
 */
export type MediaSessionFailed = { cid: bigint, peer_cid: bigint, message: string, request_id: string | null, };
