import type { UdpMode } from '@avarok/citadel-protocol-types';
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A media session is live and frames may now be sent.
 */
export type MediaSessionOpened = { cid: bigint, peer_cid: bigint, 
/**
 * True when frames travel over UDP. False means the peer connected without
 * UdpMode Enabled and there is no datagram path — the caller should tell
 * the user the call cannot start rather than silently sending nothing.
 */
unreliable: boolean, 
/**
 * Largest frame the transport will accept, so the encoder can be capped to
 * something that will actually fit rather than failing per frame.
 */
max_frame_bytes: number, request_id: string | null, };
