// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Frames were lost and the buffer has moved past them.
 *
 * Reported rather than hidden: a video decoder that has missed frames produces
 * garbage until the next keyframe, so the receiver needs this to know it should
 * ask for one instead of rendering corruption.
 */
export type MediaGapNotification = { cid: bigint, peer_cid: bigint, track: number, missing_from: number, missing_to: number, 
/**
 * Always None; routed by `cid`, as above.
 */
request_id: string | null, };
