// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One decoded-ready media frame, reassembled and released in order.
 */
export type MediaFrameNotification = { cid: bigint, peer_cid: bigint, track: number, kind: number, sequence: number, timestamp: number, flags: number, payload: number[], 
/**
 * Always None: frames are unsolicited, and like MessageNotification they are
 * routed to the right tab by `cid`, never by the request that started the
 * call. The field exists because every response variant carries one.
 */
request_id: string | null, };
