// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MessageType = "text" | "markdown" | "live_document" | "file_transfer" | "system_notice";
