// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MessageStatus } from "./MessageStatus";
import type { TransferState } from "./TransferState";

/**
 * What a window may change on a message it did not author the content of:
 * delivery state and file-transfer progress. Absent fields are left alone.
 */
export type MessagePatch = { status?: MessageStatus, error?: string, transfer_state?: TransferState, transfer_progress?: number, virtual_path?: string, file_thumbnail?: string, };
