// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NoticeKind } from "./NoticeKind";
import type { NoticeTarget } from "./NoticeTarget";

/**
 * One OS notification to raise.
 */
export type NativeNotice = { cid: bigint, kind: NoticeKind, title: string, 
/**
 * The message text only when the account shows previews; otherwise a
 * description of what happened.
 */
body: string, target: NoticeTarget, request_id: string | null, };
