// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a notification about a message reads: who sent it, or also what it says.
 */
export type NotificationPreview = "SenderOnly" | "Text";
