// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountRow } from "./AccountRow";

/**
 * The account rows, on subscribing and whenever one changes.
 */
export type NoticeRows = { 
/**
 * 0: the rows are every account's, not one session's.
 */
cid: bigint, rows: Array<AccountRow>, request_id: string | null, };
