// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a click on a notice opens. The client builds the URL from its own
 * origin; this names the account, its workspace server and the target only.
 * It never carries message content: a link is shareable and lands in history.
 */
export type NoticeTarget = { account: string, 
/**
 * The workspace server as the user typed it; absent from older sessions.
 */
server_host: string | null, 
/**
 * `conversation:<peer>`, `call:<peer>` or `requests`.
 */
open: string, };
