// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A notice-plane request was refused: no token configured, or the wrong one.
 */
export type NoticeFailure = { cid: bigint, message: string, request_id: string | null, };
