// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a notice is about.
 */
export type NoticeKind = "Message" | "PeerRequest" | "GroupInvite" | "FileOffer" | "IncomingCall";
