// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether anything on the agent's side shows its native notices, told to every
 * window that declared it hosts no ILM of its own: on declaring (in
 * `AgentCapabilities::notices_heard`) and here whenever it changes -- the
 * menu-bar app subscribed, or its connection went away.
 *
 * A window that leaves a hosted message to the agent must know someone will
 * show it: Windows and Linux have no notifier, so there the window shows it.
 */
export type NoticesHeardNotification = { 
/**
 * 0: the notice plane is the agent's, not a session's.
 */
cid: bigint, heard: boolean, request_id: string | null, };
