// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The network path a peer connection's traffic takes, settled before success is reported.
 */
export type P2pPathReport = "direct" | "turn" | "server_relay";
