// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatSecurityLevel } from "./ChatSecurityLevel";

/**
 * One chat's minimum: offers from `peer_cid` below `level` are declined.
 */
export type PeerSecurityMinimum = { peer_cid: bigint, level: ChatSecurityLevel, };
