// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PeerConnectAcceptSuccess = { cid: bigint, peer_cid: bigint, 
/**
 * Which answer was delivered: `true` accepted the connection, `false`
 * refused it.
 *
 * Without this the name is the whole message, and it says "success" for
 * both — accurate about delivery, silent about the outcome. A receiver
 * could not tell "they accepted" from "your refusal was sent".
 *
 * `PeerRegisterRespond` had exactly that shape and it was a live defect:
 * declining a registration ran the frontend's acceptance path, marked the
 * declined peer registered, and had auto-connect open a connection to the
 * person just refused.
 */
accept: boolean, request_id: string | null, };
