// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PeerConnectNotification = { cid: bigint, peer_cid: bigint, session_security_settings: any, udp_mode: any, request_id: string | null, };
