// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PeerInformation = { cid: bigint, online_status: boolean, name: string | null, username: string | null, };
