// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { P2pPathReport } from "./P2pPathReport";

/**
 * The path of an established peer connection changed: a direct (or TURN) path attached, it was
 * lost and traffic fell back to the server relay, or the background upgrade gave up. Messages
 * keep flowing, in order, across every change. Unsolicited: route it by `cid`.
 */
export type PeerPathChangedNotification = { cid: bigint, peer_cid: bigint, path: P2pPathReport, 
/**
 * Whether a background upgrade may still move the connection off the server relay.
 */
upgrading: boolean, 
/**
 * Always `None`: path changes are not answers to a request.
 */
request_id: string | null, };
