// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IceServer } from "./IceServer";
import type { TurnPolicy } from "./TurnPolicy";

/**
 * The TURN relay configuration for one `PeerConnect` attempt.
 */
export type PeerTurnConfig = { policy: TurnPolicy, ice_servers: Array<IceServer>, 
/**
 * Unix seconds after which the credentials are no longer valid. An expired config is
 * treated as no config at all.
 */
expires_at: bigint, };
