import type { UdpMode,SessionSecuritySettings } from '@avarok/citadel-protocol-types';
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PeerConnectNotification = { cid: bigint, peer_cid: bigint, session_security_settings: SessionSecuritySettings, udp_mode: UdpMode, request_id: string | null, 
/**
 * The agent answers this offer itself -- accepts, declines, or leaves it
 * unanswered by the UI's own rules -- so no window may answer it. Set for an
 * account the agent hosts, which is reachable with no window open. An
 * agent that predates this never sends it, which is what `false` means.
 */
answered_by_agent: boolean, };
