// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { P2pPathReport } from "./P2pPathReport";

export type PeerConnectSuccess = { cid: bigint, peer_cid: bigint, 
/**
 * Which path the connection's traffic takes, read once the path is settled.
 */
path: P2pPathReport, request_id: string | null, };
