// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Retention } from "./Retention";

export type PeerRetention = { peer_cid: bigint, retention: Retention, };
