import type { UdpMode,SessionSecuritySettings } from '@avarok/citadel-protocol-types';
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PeerConnectNotification = { cid: bigint, peer_cid: bigint, session_security_settings: SessionSecuritySettings, udp_mode: UdpMode, request_id: string | null, };
