import type { MessageGroupKey } from '@avarok/citadel-protocol-types';
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An invitation to a group, still unanswered: who asked, and which group.
 */
export type PendingGroupInvite = { peer_cid: bigint, group_key: MessageGroupKey, };
