// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PickFileSuccess = { cid: bigint, 
/**
 * The full path to the selected file
 */
file_path: string, 
/**
 * The file name (without path)
 */
file_name: string, 
/**
 * The file size in bytes
 */
file_size: bigint, request_id: string | null, };
