// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One reactor's one emoji on a message; retractions stay as `active: false`.
 */
export type Reaction = { emoji: string, reactorCid: bigint, at: number, active: boolean, };
