// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Recovery codes, formatted for display. Shown to the user once; never logged and never
 * stored by the agent, and wiped from memory when dropped.
 */
export type RecoveryCodes = Array<string>;
