// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RecoveryCodes } from "./RecoveryCodes";

export type RegisterSuccess = { cid: bigint, request_id: string | null, 
/**
 * The account's recovery codes, to show the user once. Empty for a server without
 * post-quantum sign-in. With `connect_after_register` this response is sent before the
 * connect's own.
 */
recovery_codes: RecoveryCodes, };
