// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How long a conversation keeps its messages.
 */
export type Retention = "Forever" | { "Days": number };
