// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SecurityKeyPurpose } from "./SecurityKeyPurpose";

/**
 * The SDK needs a security-key touch. The window runs WebAuthn `get` with
 * `allowCredentials = allowed_credential_ids` and the PRF extension evaluated at `prf_salt`,
 * then answers with `SecurityKeyAnswer` (or `SecurityKeyDecline`).
 *
 * `request_id` is the request of the window that asked (its `Connect` or
 * `SignInManagement`). `cid` is the session's, or 0 for a sign-in, which has none yet.
 */
export type SecurityKeyChallengeNotification = { cid: bigint, request_id: string | null, 
/**
 * Names this challenge in the answer.
 */
challenge_id: string, purpose: SecurityKeyPurpose, allowed_credential_ids: Array<Array<number>>, 
/**
 * 32 bytes: the PRF `eval.first` input.
 */
prf_salt: Array<number>, 
/**
 * How long the SDK waits for the touch. An answer after that is refused.
 *
 * `bigint`, as every u64 is: the WASM client serializes with
 * `serialize_large_number_types_as_bigints`, so a page receives a BigInt here, and a
 * `number` type let it do arithmetic that threw (the touch prompt crashed in render).
 */
expires_in_ms: bigint, };
