// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The agent handed the answer to the SDK. Whether it signs in is the server's to decide, and
 * the outcome is the asking request's own response.
 */
export type SecurityKeyAnswerSuccess = { cid: bigint, request_id: string | null, challenge_id: string, };
