// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The answer was not used: the challenge is unknown, already answered or expired, the window
 * was not asked, the credential was not one of the allowed ones, or the PRF output is not 32
 * bytes. A refused answer leaves the challenge open for a valid one.
 */
export type SecurityKeyAnswerFailure = { cid: bigint, request_id: string | null, challenge_id: string, message: string, };
