// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why the agent is asking for a touch.
 */
export type SecurityKeyPurpose = "SignIn" | "StepUp" | "Enrol";
