// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A `SendReliable` was accepted by the session's ILM: it is stored and will be
 * retransmitted until the peer acknowledges it. Not "delivered".
 */
export type SendReliableAccepted = { cid: bigint, peer_cid: bigint, request_id: string | null, };
