// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The message is in the agent's durable outbound queue; ILM delivers it and
 * retries until the peer acknowledges it. Not a delivery receipt.
 */
export type SendReliableSuccess = { cid: bigint, peer_cid: bigint, request_id: string | null, };
