// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ServerConnectionLost = { cid: bigint, 
/**
 * Whether the agent is trying to get the link back.
 */
reconnecting: boolean, request_id: string | null, };
