// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ServiceConnectionAccepted = { cid: bigint, request_id: string | null, 
/**
 * This agent hosts a session's ILM and conversations for a connection that
 * declares `agent_ilm` (multi-window, 0.8.6). Said in the greeting, the
 * first thing on every socket, so a client knows at once whether to
 * declare: an older agent does not answer a declaration at all. Its
 * greeting has no such field, which is what `false` means here.
 */
agent_ilm: boolean, 
/**
 * This agent supervises its hosted accounts' peer connections (redialling them with
 * no window open), so a window must not auto-connect for them: it sends
 * `ConfigCommand::Interest` instead. Absent from an older agent's greeting, which is
 * what `false` means.
 */
supervises_p2p: boolean, };
