import type { PeerSessionInformation } from "./PeerSessionInformation";
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SessionInformation = { cid: bigint, username: string, server_address: string, peer_connections: Record<string, PeerSessionInformation>, 
/**
 * The `host[:port]` the account registered to, as the user typed it (a hosted
 * tenant as `acme.work.avarok.net`, an IP as the IP). The resolved address
 * (`SessionInformation::server_address`) is, behind an edge, shared by many
 * workspaces. `None` for an account registered before the agent recorded it.
 */
server_host: string | null, };
