// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What one attached connection is to a session.
 */
export type SessionRole = "Primary" | "Secondary" | "Detached";
