import type { PeerSessionInformation } from "./PeerSessionInformation";
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SessionInformation = { cid: bigint, username: string, peer_connections: Record<string, PeerSessionInformation>, };
