// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionRole } from "./SessionRole";

/**
 * Sent to each attached connection whenever the set of attached connections
 * changes, and only then: a session nobody else ever joins never sends one,
 * so a UI that predates this never sees it from its own session.
 */
export type SessionRoleNotification = { cid: bigint, role: SessionRole, 
/**
 * How many connections are attached now, this one included (0 if detached).
 */
attached: number, request_id: string | null, };
