// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionRole } from "./SessionRole";

/**
 * `AttachSession` succeeded: this connection now receives the session.
 */
export type SessionAttached = { cid: bigint, role: SessionRole, 
/**
 * Proves a later attach to this session without the password. Lives as
 * long as the session does, in the agent's memory only.
 */
token: number[], request_id: string | null, };
