// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Returned when a Connect request is made for a session that is already active.
 * This allows the frontend to gracefully handle the case where the user is already
 * connected (e.g., from another tab or auto-reconnect) without treating it as an error.
 */
export type SessionAlreadyActive = { cid: bigint, username: string, message: string, request_id: string | null, };
