// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SignInManagementOutcome } from "./SignInManagementOutcome";

/**
 * What a `SignInManagement` request did. For `RegenerateRecoveryCodes` the outcome holds the
 * new codes, which is the only time they can be shown.
 */
export type SignInManagementSuccess = { cid: bigint, request_id: string | null, outcome: SignInManagementOutcome, };
