// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A session the agent removed because its server would not take it back, kept so a UI that
 * was not attached at the time can say "signed out by the server, sign in again".
 */
export type SignedOutSession = { cid: bigint, username: string, 
/**
 * What `ServerReconnectFailed` said.
 */
reason: string, };
