// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RecoveryCodes } from "./RecoveryCodes";
import type { SignInCredential } from "./SignInCredential";
import type { SignInPolicy } from "./SignInPolicy";

/**
 * What a management change did (`citadel_types::auth::SignInManagementOutcome`). The new
 * recovery codes are [`RecoveryCodes`], which never print.
 */
export type SignInManagementOutcome = { "Credentials": { policy: SignInPolicy, credentials: Array<SignInCredential>, } } | { "Added": { id: number, } } | "Renamed" | "Removed" | "PolicySet" | { "RecoveryCodes": RecoveryCodes };
