// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StageUploadChunkFailure = { cid: bigint, upload_id: string, message: string, request_id: string | null, };
