// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One chunk of a browser file being staged on the agent, so a file of any size
 * up to the staging ceiling can be sent without being held whole in one frame.
 * Chunks arrive in order (`offset` equals what the agent has received) and the
 * browser sends the next only after this one is acknowledged: that wait is the
 * backpressure.
 */
export type StageUploadChunkSuccess = { cid: bigint, upload_id: string, 
/**
 * Bytes of the file the agent now holds.
 */
received: bigint, request_id: string | null, };
