// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The factors a window offers to prove the account again before a change to its sign-in
 * factors. A session signed in with a recovery code offers none.
 */
export type StepUp = { password: number[] | null, 
/**
 * Whether the window can answer a [`SecurityKeyChallengeNotification`]. Adding a key
 * needs it (the new key's touch) even when the step-up itself is the password alone.
 */
security_key: boolean, };
