// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SupervisorState } from "./SupervisorState";

/**
 * Unsolicited: route it by `cid`.
 */
export type SupervisorNotification = { cid: bigint, 
/**
 * The peer it is about; absent when it is about the account's server link.
 */
peer_cid: bigint | null, state: SupervisorState, 
/**
 * Always `None`: supervisor events are not answers to a request.
 */
request_id: string | null, };
