// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where the supervisor has got to, for the account or, with a `peer_cid`, for one peer.
 */
export type SupervisorState = "Healing" | "Healed" | "Degraded";
