// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UpdateAvailable } from "./UpdateAvailable";

/**
 * Where the updater stands, answered to every update request.
 */
export type UpdateStatus = { cid: bigint, current: string, 
/**
 * The newer release, if one was found.
 */
available: UpdateAvailable | null, 
/**
 * "Automatically install updates when no account is signed in".
 */
auto_install: boolean, 
/**
 * When the last check finished, in seconds since the Unix epoch.
 */
last_checked: bigint | null, 
/**
 * Why the last check, download, verification or install did not succeed.
 */
last_error: string | null, request_id: string | null, };
