// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A release newer than the running agent.
 */
export type UpdateAvailable = { 
/**
 * 0: an update is the agent's, not one session's.
 */
cid: bigint, 
/**
 * The running version, `X.Y.Z`.
 */
current: string, 
/**
 * The release's version, `X.Y.Z`.
 */
latest: string, 
/**
 * The release page on GitHub.
 */
notes_url: string, 
/**
 * What to download by hand when this agent cannot install it itself: the asset for this
 * install, or the release page when none fits.
 */
download_url: string, 
/**
 * Downloaded and verified: "Restart to update" installs it now. False: link out only.
 */
ready: boolean, 
/**
 * The download carried a valid ML-DSA-65 (post-quantum) signature by the release key, over
 * this release's tag, the file's name and its sha256. Nothing is staged without it, and
 * without it `ready` is false and `UpdateStatus::last_error` (prefixed "ML-DSA:") says why.
 */
mldsa_verified: boolean, request_id: string | null, };
