// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * To the menu-bar app only (it owns the bundle): install the verified disk image at `path`,
 * which holds version `version`, then relaunch.
 */
export type UpdateInstall = { cid: bigint, version: string, path: string, request_id: string | null, };
