//! What ILM costs the SDK, with the traffic reductions off and on.
//!
//! Two real agents over loopback, and a conversation built from payloads the
//! UI actually produces (`fixtures/traffic`, generated by the compression
//! study from the UI's own serialisers): a chat exchange with typing
//! indicators and delivery receipts, a burst of Yjs updates, and a snapshot.
//! Every `InternalServiceRequest::Message` a messenger hands its agent is one
//! SDK message on the wire (plus the SDK's own ack for it), so counting those
//! at the agent boundary counts what the network carries.
//!
//! The run asserts that the reductions reduce, and prints the numbers.

#![cfg(all(
    not(target_arch = "wasm32"),
    feature = "compression-brotli",
    feature = "compression-deflate"
))]

use citadel_internal_service_test_common as common;

use citadel_internal_service_connector::messenger::{
    CompressionHint, DynamicCompression, IlmOptions,
};
use citadel_io::tokio;
use std::sync::Arc;
use std::time::Duration;

mod traffic_support;
use traffic_support::{
    expect, fixtures, send, two_agents, Tally, SDK_ACK_WIRE, SDK_MESSAGE_OVERHEAD,
};

#[derive(Debug, Clone, Copy)]
struct Cost {
    messages: usize,
    app_bytes: usize,
}

impl Cost {
    fn between(from: (usize, usize), to: (usize, usize)) -> Self {
        Self {
            messages: to.0 - from.0,
            app_bytes: to.1 - from.1,
        }
    }
}

/// The whole run, and the two halves of it.
#[derive(Debug, Clone, Copy)]
struct Run {
    chat: Cost,
    yjs: Cost,
    total: Cost,
}

impl Cost {
    fn estimated_wire_bytes(self) -> usize {
        self.app_bytes + self.messages * (SDK_MESSAGE_OVERHEAD + SDK_ACK_WIRE)
    }
}

/// Runs the workload between two fresh agents and returns what both sides sent.
async fn workload(options: IlmOptions) -> Run {
    let tally = Arc::new(Tally::default());
    let (a, b) = two_agents(options, options, &tally).await;
    let (tx_a, mut rx_a, cid_a) = (a.tx, a.rx, a.cid);
    let (tx_b, mut rx_b, cid_b) = (b.tx, b.rx, b.cid);
    // Let the opening Polls (and their advertisements) cross before measuring.
    tokio::time::sleep(Duration::from_secs(1)).await;
    let before = tally.read();

    let typing = fixtures("ctrl__typing").remove(0);
    let receipt = fixtures("ctrl__ack_delivered").remove(0);
    for (i, chat) in fixtures("chat__").iter().enumerate() {
        let (from, to, rx_to, rx_from, id_from, id_to) = if i % 2 == 0 {
            (&tx_a, cid_b, &mut rx_b, &mut rx_a, cid_a, cid_b)
        } else {
            (&tx_b, cid_a, &mut rx_a, &mut rx_b, cid_b, cid_a)
        };
        let reply = if i % 2 == 0 { &tx_b } else { &tx_a };
        send(from, to, &typing, CompressionHint::CborCommand).await;
        send(from, to, chat, CompressionHint::CborCommand).await;
        expect(rx_to, id_from, chat).await;
        send(reply, id_from, &receipt, CompressionHint::CborCommand).await;
        expect(rx_from, id_to, &receipt).await;
    }
    let after_chat = settle(&tally).await;
    for update in fixtures("yjs-inc__") {
        send(&tx_a, cid_b, &update, CompressionHint::YjsUpdate).await;
        expect(&mut rx_b, cid_a, &update).await;
    }
    let snapshot = fixtures("yjs-snap__").remove(0);
    send(&tx_b, cid_a, &snapshot, CompressionHint::YjsUpdate).await;
    expect(&mut rx_a, cid_b, &snapshot).await;

    let end = settle(&tally).await;
    Run {
        chat: Cost::between(before, after_chat),
        yjs: Cost::between(after_chat, end),
        total: Cost::between(before, end),
    }
}

/// Until the last ACKs have gone out and nothing more moves.
async fn settle(tally: &Tally) -> (usize, usize) {
    let mut last = tally.read();
    loop {
        tokio::time::sleep(Duration::from_millis(500)).await;
        let now = tally.read();
        if now == last {
            return now;
        }
        last = now;
    }
}

#[tokio::test(flavor = "multi_thread")]
async fn the_reductions_cut_sdk_messages_and_bytes() {
    common::setup_log();
    let off = workload(IlmOptions::LEGACY).await;
    let on = workload(IlmOptions {
        piggyback_acks: true,
        dynamic_compression: DynamicCompression::All,
    })
    .await;

    let pct = |a: usize, b: usize| 100.0 * (1.0 - b as f64 / a as f64);
    for (phase, off, on) in [
        ("chat (60 CBOR frames)", off.chat, on.chat),
        ("yjs (updates + snapshot)", off.yjs, on.yjs),
        ("total", off.total, on.total),
    ] {
        println!(
            "[ILM-TRAFFIC] {phase}: off {} msgs / {} app B / ~{} wire B; on {} msgs / {} app B / ~{} wire B; saved {:.1}% msgs, {:.1}% app B, ~{:.1}% wire B",
            off.messages,
            off.app_bytes,
            off.estimated_wire_bytes(),
            on.messages,
            on.app_bytes,
            on.estimated_wire_bytes(),
            pct(off.messages, on.messages),
            pct(off.app_bytes, on.app_bytes),
            pct(off.estimated_wire_bytes(), on.estimated_wire_bytes())
        );
    }
    assert!(
        on.total.messages < off.total.messages,
        "piggybacking sent no fewer messages: {off:?} vs {on:?}"
    );
    assert!(
        on.yjs.app_bytes < off.yjs.app_bytes,
        "compression sent no fewer bytes: {off:?} vs {on:?}"
    );
}
